name: develop CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: get Github Repository
        uses: actions/checkout@v4

      - name: install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Create resources directory if it does not exist
        run: mkdir -p ./src/main/resources

      - name: create application.yml
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml

      - name: test and build
        run: ./gradlew clean build

      - name: change build file name
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: send build file to EC2 with SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.jar
          target: /home/ec2-user/yesable_server/tobe

      - name: connect to EC2 with SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_PRIVATE_KEY }}
            envs: APPLICATION_PROPERTIES
            script_stop: true
            script: |
              # Remove old current directory
              rm -rf /home/***/yesable_server/current
  
              # Create parent directories if they do not exist, then create the current directory
              sudo mkdir -p /home/***/yesable_server/current              
              
              # Move the JAR file to the new current directory
              mv /home/***/yesable_server/tobe/project.jar /home/***/yesable_server/current/project.jar
  
              # Change to the current directory
              cd /home/***/yesable_server/current
  
              # Check if there is a process running on port 9475, and kill it if found
              pid=$(lsof -t -i :9475)
              if [ -n "$pid" ]; then
                echo "Killing process $pid..."
                kill $pid
              else
                echo "No process found on port 9475."
                fi
  
              # Start the new server process
              nohup java -jar project.jar --spring.profiles.active=local > ~/yesable_server/logs/server.log 2>&1 &
  
              # Remove old 'tobe' directory
              rm -rf /home/***/yesable_server/tobe
